"""add_anomaly_models

Revision ID: f77968dcd638
Revises: 3535ec4fe300
Create Date: 2026-09-24 22:16:16.791284

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f77968dcd638"
down_revision: str | Sequence[str] | None = "3535ec4fe300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalies",
        sa.Column(
            "movement_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "item_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "score",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomalies_item_id"), "anomalies", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_anomalies_movement_id"), "anomalies", ["movement_id"], unique=False
    )
    op.create_table(
        "anomaly_alerts",
        sa.Column(
            "anomaly_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "message",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["anomaly_id"],
            ["anomalies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomaly_alerts_anomaly_id"),
        "anomaly_alerts",
        ["anomaly_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_anomaly_alerts_anomaly_id"),
        table_name="anomaly_alerts",
    )
    op.drop_table(
        "anomaly_alerts",
    )
    op.drop_index(
        op.f("ix_anomalies_movement_id"),
        table_name="anomalies",
    )
    op.drop_index(
        op.f("ix_anomalies_item_id"),
        table_name="anomalies",
    )
    op.drop_table("anomalies")
    # ### end Alembic commands ###
