from pydantic import BaseModel, ConfigDict, Field


class RFC7807Error(BaseModel):
    """
    Standard API Error Response based on RFC 7807 (Problem Details for HTTP APIs).
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "The request is invalid.",
                "instance": "/api/v1/items",
            }
        }
    )

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        ..., description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        ..., description="The HTTP status code generated by the origin server."
    )
    detail: str = Field(
        ..., description="A human-readable explanation specific to this occurrence."
    )
    instance: str | None = Field(
        default=None,
        description="URI identifying the specific occurrence of the problem.",
    )
